version: "3.3"

services:
  postgres:
    image: postgres:16.2-alpine3.19
    environment:
      - POSTGRES_DB=habits_db
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_password
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./init_scripts:/docker-entrypoint-initdb.d
      - habits_db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    secrets:
      - db_password

secrets:
  db_password:
    file: ./db_secrets/db_password.txt

volumes:
  habits_db-data:
